tap "oven-sh/bun"
brew "bat"
brew "clang-format"
brew "deno"
brew "dust"
brew "go"
brew "golangci-lint"
brew "hadolint"
brew "hugo"
brew "node"
brew "p7zip"
brew "ripgrep"
brew "rustup"
brew "tmux"
brew "uv"
brew "valkey"
brew "yazi"
brew "zellij"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "oven-sh/bun/bun"
cask "claude-code"
cask "docker-desktop", args: { appdir: "/Applications" }
cask "dotnet-sdk"
cask "font-hackgen", args: { appdir: "/Applications" }
cask "ghostty"
cask "google-chrome", args: { appdir: "/Applications" }
cask "iterm2", args: { appdir: "/Applications" }
cask "steam", args: { appdir: "/Applications" }
cask "visual-studio-code", args: { appdir: "/Applications" }
vscode "bierner.markdown-mermaid"
vscode "biomejs.biome"
vscode "cardinal90.multi-cursor-case-preserve"
vscode "davidanson.vscode-markdownlint"
vscode "denoland.vscode-deno"
vscode "golang.go"
vscode "jebbs.plantuml"
vscode "narsenico.vscode-progressive-increment"
vscode "sgryjp.japanese-word-handler"
vscode "yeannylam.recenter-top-bottom"
vscode "yzhang.markdown-all-in-one"
