- name: update homebrew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  tags: homebrew_update

- name: homebrew tap
  homebrew_tap:
    name: '{{ item }}'
  with_items: '{{ homebrew_taps }}'
  tags: homebrew_tap

- name: install brews
  homebrew:
    name: '{{ item.name }}'
    state: '{{ item.state | default("latest") }}'
  with_items: '{{ homebrew_packages }}'
  tags: homebrew_brew

- name: install casks
  homebrew_cask:
    name: '{{ item.name }}'
    state: '{{ item.state | default("latest") }}'
    install_options: 'appdir=/Applications'
  with_items: '{{ homebrew_cask_packages }}'
  tags: homebrew_cask
