# - name: install python
#   shell: pyenv install -s {{ python_version }}
#   tags: python_install

# - name: set global version of python
#   shell: pyenv global {{ python_version }}
#   tags: python_set_global_version

- block:
  - shell: which poetry
    register: which_poetry_result
    ignore_errors: true
    changed_when: false

  - name: install poetry
    shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
    when: which_poetry_result is failed
  tags: python_poetry_install
