- block:
  - name: list vscode extensions
    command: code --list-extensions
    register: vscode_list_extensions
    changed_when: false
    check_mode: false

  - name: install vscode extensions
    command: code --install-extension '{{ item }}'
    with_items: '{{ vscode_extensions }}'
    when: item not in vscode_list_extensions.stdout

  tags: vscode_extensions
