- name: install nodejs via nvm
  shell: source ~/.zsh.d/nvm.sh && nvm install {{ node_version }}
  register: result
  changed_when: "'is already installed.' not in result.stderr"

- name: use nodejs version
  shell: source ~/.zsh.d/nvm.sh && nvm use {{ node_version }}
  when: "'using node {{ node_version }}' not in result.stdout"

- name: install node packages
  npm:
    name: "{{ item.name }}"
    state: present
    executable: ~/.nvm/versions/node/{{node_version}}/bin/npm
    global: yes
  with_items: "{{ node_packages }}"
