- name: install homebrew
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew
    
- name: setup brew taps
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{homebrew_taps}}"
      
- name: update brew
  homebrew: update_homebrew=yes
      
- name: install brew packages
  homebrew: name={{ item.name }} install_options={{ item.install_options | default() }} state={{ item.state | default('latest') }}
  with_items: "{{homebrew_packages}}"
      
- name: install homebrew-cask packagess
  homebrew_cask: name={{ item.name }} state=present 
  with_items: "{{homebrew_cask_packages}}"
  environment:
    HOMEBREW_CASK_OPTS: --appdir=/Applications
# install_options="appdir=/Applications
