## brew
eval "$(/opt/homebrew/bin/brew shellenv)"

## local
export PATH=~/.local/bin:$PATH

## Machine-specific settings such as the proxy, generated by chezmoi
[ -f ~/.zprofile.local ] && source ~/.zprofile.local
